package com.revx.api.payload.response.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.revx.api.payload.enums.OrderState;

/**
 * @param venueOrderId  ID of the order generated by the system.
 * @param clientOrderId Client order ID provided by the client.
 * @param state         Order state after submitting it.
 *                      Possible values: [pending_new, new, partially_filled, filled, cancelled, rejected, replaced]
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record NewOrderData(String venueOrderId,
                           String clientOrderId,
                           OrderState state) {

    @JsonCreator
    public NewOrderData(
            @JsonProperty("venue_order_id") String venueOrderId,
            @JsonProperty("client_order_id") String clientOrderId,
            @JsonProperty("state") String state) {
        this(venueOrderId, clientOrderId, OrderState.fromValue(state));
    }
}
