package com.revx.api.payload.response.order;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.revx.api.payload.enums.*;

import java.util.List;

/**
 * Details of an individual order.
 *
 * @param id                    ID of the order generated by the system
 * @param previousOrderId       ID of the previous/replaced order. Present only if this order has replaced another one
 * @param clientOrderId         ID of the order assigned by the client when creating the order
 * @param symbol                Symbol of the asset for which this order has been created
 * @param side                  Side of the order. Indicates whether the order was to acquire (buy) or dispose of (sell) an asset
 * @param orderType                  Type of the order. A market order is executed immediately at the current market price.
 *                              A limit order is executed only if the asset reaches a specified price set by the trader
 * @param quantity              Quantity of the order, expressed in base currency
 * @param filledQuantity        Quantity of the order that has been filled. How much of the order has already been executed
 * @param leavesQuantity        Quantity of the order that remains to be filled. How much of the order remains to be executed
 * @param price                 The worst price for the client at which an order will be filled.
 *                              For buy orders, it's the maximum price for the order; for sell orders, it's the minimum price
 * @param averageFillPrice      Quantity-weighted average fill price of the order.
 *                              The average price at which the order has been executed so far
 * @param state                Status of the order
 * @param rejectReason          Reason for rejecting the order, present only for state=rejected
 * @param timeInForce           Time in force of the order. Indicates how long the order should remain active
 * @param executionInstructions List of execution instructions for the order
 * @param createdDate           Timestamp in Unix epoch milliseconds when the order was created
 */
public record OrderInfo(String id,
                        String previousOrderId,
                        String clientOrderId,
                        String symbol,
                        Side side,
                        OrderType orderType,
                        String quantity,
                        String filledQuantity,
                        String leavesQuantity,
                        String price,
                        String averageFillPrice,
                        OrderState state,
                        String rejectReason,
                        String timeInForce,
                        List<ExecutionInstruction> executionInstructions,
                        Long createdDate) {

    @JsonCreator
    public OrderInfo(@JsonProperty("id") String id,
                     @JsonProperty("previous_order_id") String previousOrderId,
                     @JsonProperty("client_order_id") String clientOrderId,
                     @JsonProperty("symbol") String symbol,
                     @JsonProperty("side") String side,
                     @JsonProperty("type") String type,
                     @JsonProperty("quantity") String quantity,
                     @JsonProperty("filled_quantity") String filledQuantity,
                     @JsonProperty("leaves_quantity") String leavesQuantity,
                     @JsonProperty("price") String price,
                     @JsonProperty("average_fill_price") String averageFillPrice,
                     @JsonProperty("status") String status,
                     @JsonProperty("reject_reason") String rejectReason,
                     @JsonProperty("time_in_force") String timeInForce,
                     @JsonProperty("execution_instructions") List<String> executionInstructions,
                     @JsonProperty("created_date") Long createdDate) {
        this(
                id,
                previousOrderId,
                clientOrderId,
                symbol,
                Side.fromValue(side),
                OrderType.fromValue(type),
                quantity,
                filledQuantity,
                leavesQuantity,
                price,
                averageFillPrice,
                OrderState.fromValue(status),
                rejectReason,
                timeInForce,
                executionInstructions != null
                        ? executionInstructions.stream()
                        .map(ExecutionInstruction::fromValue)
                        .toList()
                        : null,
                createdDate
        );
    }
}
